export const supportedLangueges = {
    "English": "en",
    "French": "fr",
    "Spanish": "es",
    "German": "de",
    "Italian": "it",
    "Portuguese": "pt",
    "Chinese (Simplified)": "zh-CN",
    "Chinese (Traditional)": "zh-TW",
    "Japanese": "ja",
    "Korean": "ko",
    "Russian": "ru",
    "Arabic": "ar",
    "Hindi": "hi",
    "Dutch": "nl",
    "Polish": "pl",
    "Swedish": "sv",
    "Danish": "da",
    "Finnish": "fi",
    "Greek": "el",
    "Hebrew": "he",
    "Hungarian": "hu",
    "Indonesian": "id",
    "Norwegian": "no",
    "Turkish": "tr",
    "Vietnamese": "vi",
    "Thai": "th",
    "Czech": "cs",
    "Romanian": "ro",
    "Bulgarian": "bg",
    "Slovak": "sk",
    "Croatian": "hr",
    "Serbian": "sr",
    "Ukrainian": "uk",
    "Malay": "ms",
    "Catalan": "ca",
    "Filipino": "tl",
    "Lithuanian": "lt",
    "Latvian": "lv",
    "Slovenian": "sl",
    "Estonian": "et",
    "Icelandic": "is",
    "Irish": "ga",
    "Welsh": "cy",
    "Maltese": "mt"
};